name: Deploy Firebase

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '14'

      - name: Install dependencies
        run: npm install

      - name: Set Firebase API Key
        env:
          FIREBASE_API_KEY: ${{ secrets.FIREBASE_API_KEY }}  # Передаем секрет как переменную окружения
        run: |
          echo "Setting up Firebase configuration"
          node setupFirebase.js  # В вашем коде Firebase будет настроен с этим API ключом
